### ISSUE TITLE
Easy accessible GUI 

### ISSUE THREAD

**Issue by a1300** [AschPlatform/asch-frontend-2#84]
Dear @lbgod2222, @dujunhui007, @CaosBad

the most important thing first: 
The new ASCH GUI is extremly pretty and easy to use with very nice animations :+1: 

### Question
In the past the GUI was integrated in the main [asch](http://github.com/aschplatform/asch) repo. Now it is in this repo. However, for new ASCH developers it isn't so convenient to download and build __asch__ and  __asch-frontend-2__.

Has the __asch-frontend-2__ a build server where the __asch__ users could download the __asch-frontend-2__ build files directly into the `asch/public/dist` folders?

That would make it more easier to use ASCH

All the best
a1300

**Comment by dujunhui007** [comment]
Thank you for your compliment. The new front-end warehouse address is here.---https://github.com/AschPlatform/asch-frontend-2,
modify this file .https://github.com/AschPlatform/asch-frontend-2/blob/develop/src/utils/constants.js

**Comment by CaosBad** [comment]
Check this [repo](https://github.com/AschPlatform/asch-frontend-2) and change this [code](https://github.com/AschPlatform/asch-frontend-2/blob/master/src/utils/constants.js#L87) with your local asch server address , install package and use `npm run` or `npm build`  to test.

**Comment by a1300** [comment]
@CaosBad thank you for you reply.

I already did this, but this is way too complicated for a new ASCH developer to do. 

I prefer a solution, very similar to the __old__ asch-frontend where I can create a __asch-frontend-2` build for `localnet`, `testnet` and `mainnet`. Is that ok for you? If yes, I will provide an pull request

**Comment by CaosBad** [comment]
OK

**Comment by a1300** [comment]
@CaosBad superb.

1. How do you run __asch-frontend-2__ in the various (`localnet`, `testnet`, `frontend`) configurations?
1.1 Do you also have __asch-frontnend-2__ running on port `4096` on `localhost` ?
2. What are the pre-configured IP's for  `localnet`, `testnet`, `frontend` ? Is this correct?
2.1 `mainet`: https://wallet.asch.io/api/blocks
2.2. `testnet`: http://testnet.asch.io/api/peers/version
2.3 `localnet`: http:localhost:4096

**Comment by CaosBad** [comment]
I think cmd or package script could be a good way to solve this problem ，will be add in this week
